### ISSUE TITLE
ToConsoleColor does not work with DarkGray

### ISSUE THREAD

**Issue by scott-xu** [david-von-tamar/ansi-term#3]
Method: ToConsoleColor
Input: Color.DarkGray
Output: ConsoleColor.Gray
Expected: ConsoleColor.DarkGray

**Comment by scott-xu** [comment]
Never mind. The Color.DarkGray is not the same with ConsoleColor.DarkGray.

**Comment by davidvontamar** [comment]
> Never mind. The Color.DarkGray is not the same with ConsoleColor.DarkGray.

That's a relief. Have you experienced more problems with color?

**Comment by scott-xu** [comment]
No, it works perfectly. Thanks!
